/*
:description: batScript lib Bool: 布尔类型标准库 
:file: Bool.bs
:author: WateRun
:time: 2025-09-07
*/

/*
:description: 判断对应的布尔值是否是缺省布尔值 
:param bool_value: 被判断的布尔值
:return: 是否是缺省布尔值
*/
func isDefault(bool_value: bool) -> bool
{
    return !bool_value; # 缺省值为false
}

func getDefault() -> bool;
func parseToBool() -> bool;
func getFirstUpperStr() ->;
func getAllUpperStr() ->;
func getAllLowerStr() ->;
