func create(file: str, pwd: num);
func destroy(file: str, pwd: num);

func setNum();
func getNum();
func hasNum();
func delNum();
func matchNum
func setStr();
func getStr();
func hasStr();
func delStr();
func setBool();
func getBool();
func hasBool();
func delBool();
func setNumArray();
func getNumArray();
func hasNumArray();
func delNumArray();
func setStrArray();
func getStrArray();
func hasStrArray();
func delStrArray();
func setBoolArray();
func getBoolArray();
func hasBoolArray();
func delBoolArray();

func getSimpDBInfo();
